import type { MovementFamily } from './types';

const seededAt = new Date('2026-08-20T18:00:00.000Z').getTime();
type Seed = Pick<MovementFamily, 'id' | 'name' | 'aliases' | 'primaryMuscles' | 'secondaryMuscles'>;

const seeds: Seed[] = [
  ['horizontal_press', 'Horizontal Press', ['卧推类'], ['chest'], ['triceps', 'front_delts']], ['incline_press', 'Incline Press', ['上斜推'], ['upper_chest'], ['triceps', 'front_delts']], ['vertical_press', 'Vertical Press', ['过顶推'], ['front_delts'], ['triceps']], ['fly', 'Fly', ['夹胸'], ['chest'], ['front_delts']], ['lateral_raise', 'Lateral Raise', ['侧平举'], ['side_delts'], []], ['rear_delt_fly', 'Rear Delt Fly', ['反向飞鸟'], ['rear_delts'], ['upper_back']], ['vertical_pull', 'Vertical Pull', ['下拉类'], ['lats'], ['biceps', 'upper_back']], ['horizontal_row', 'Horizontal Row', ['划船类'], ['upper_back'], ['lats', 'biceps']], ['high_row', 'High Row', ['高位划船'], ['upper_back'], ['rear_delts', 'biceps']], ['squat', 'Squat', ['深蹲类'], ['quads'], ['glutes', 'hamstrings']], ['leg_press', 'Leg Press', ['腿举'], ['quads'], ['glutes']], ['hip_hinge', 'Hip Hinge', ['髋铰链'], ['glutes'], ['hamstrings', 'erectors']], ['hip_extension', 'Hip Extension', ['髋伸展'], ['glutes'], ['hamstrings']], ['knee_extension', 'Knee Extension', ['腿屈伸'], ['quads'], []], ['knee_flexion', 'Knee Flexion', ['腿弯举'], ['hamstrings'], []], ['hip_abduction', 'Hip Abduction', ['髋外展'], ['abductors'], ['glutes']], ['hip_adduction', 'Hip Adduction', ['髋内收'], ['adductors'], []], ['calf_raise', 'Calf Raise', ['提踵'], ['calves'], []], ['elbow_flexion', 'Elbow Flexion', ['弯举'], ['biceps'], ['forearms']], ['elbow_extension', 'Elbow Extension', ['伸肘'], ['triceps'], []], ['core_flexion', 'Core Flexion', ['卷腹'], ['abs'], ['obliques']], ['core_stability', 'Core Stability', ['核心稳定'], ['abs'], ['obliques']]
].map(([id, name, aliases, primaryMuscles, secondaryMuscles]) => ({ id, name, aliases, primaryMuscles, secondaryMuscles } as Seed));

export const movementFamilySeeds: MovementFamily[] = seeds.map(item => ({ ...item, category: null, description: null, status: 'active', createdAt: seededAt, updatedAt: seededAt }));
export const movementFamilyAssignments = [
  ['bench_press', 'horizontal_press', 'primary'], ['incline_bench_press', 'incline_press', 'primary'], ['dumbbell_fly', 'fly', 'primary'], ['push_up', 'horizontal_press', 'primary'], ['dumbbell_bench_press', 'horizontal_press', 'primary'], ['deadlift', 'hip_hinge', 'primary'], ['pull_up', 'vertical_pull', 'primary'], ['barbell_row', 'horizontal_row', 'primary'], ['lat_pulldown', 'vertical_pull', 'primary'], ['seated_cable_row', 'horizontal_row', 'primary'], ['dumbbell_row', 'horizontal_row', 'primary'], ['overhead_press', 'vertical_press', 'primary'], ['dumbbell_shoulder_press', 'vertical_press', 'primary'], ['lateral_raise', 'lateral_raise', 'primary'], ['front_raise', 'vertical_press', 'primary'], ['face_pull', 'rear_delt_fly', 'primary'], ['barbell_curl', 'elbow_flexion', 'primary'], ['dumbbell_curl', 'elbow_flexion', 'primary'], ['triceps_pushdown', 'elbow_extension', 'primary'], ['skull_crusher', 'elbow_extension', 'primary'], ['hammer_curl', 'elbow_flexion', 'primary'], ['squat', 'squat', 'primary'], ['leg_press', 'leg_press', 'primary'], ['romanian_deadlift', 'hip_hinge', 'primary'], ['leg_extension', 'knee_extension', 'primary'], ['leg_curl', 'knee_flexion', 'primary'], ['goblet_squat', 'squat', 'primary'], ['lunge', 'squat', 'primary'], ['calf_raise', 'calf_raise', 'primary'], ['crunch', 'core_flexion', 'primary'], ['plank', 'core_stability', 'primary'], ['hanging_leg_raise', 'core_flexion', 'primary'], ['russian_twist', 'core_flexion', 'primary'], ['hack_squat', 'squat', 'primary'], ['hip_thrust', 'hip_extension', 'primary'], ['pec_deck', 'fly', 'primary'], ['machine_chest_press', 'horizontal_press', 'primary'], ['reverse_pec_deck', 'rear_delt_fly', 'primary'], ['cable_lateral_raise', 'lateral_raise', 'primary'], ['high_row', 'high_row', 'primary'], ['cable_crunch', 'core_flexion', 'primary'], ['bulgarian_split_squat', 'squat', 'primary'], ['hip_abduction', 'hip_abduction', 'primary'], ['hip_adduction', 'hip_adduction', 'primary'],
] as const;
