import type { GymFlowStore } from '../../db/types'; import { createCandidateResolutionService } from '../candidate-resolution'; import type { CompatibilityIssue, ExerciseGymCompatibilityStatus, ExerciseGymMatchResult, MatchExerciseToGymInput, RequirementGroupEvaluation } from './types';
const rank: Record<ExerciseGymCompatibilityStatus, number> = { executable: 3, executable_with_warning: 2, not_executable: 1 };
export function createMatchingService(store: Pick<GymFlowStore, 'gyms' | 'inventory' | 'exercises' | 'taxonomy' | 'substitutions'>) {
  const evaluate = async (exerciseId: string, gymId: string, input: MatchExerciseToGymInput): Promise<Omit<ExerciseGymMatchResult, 'alternatives'>> => {
    const [exercise, gym] = await Promise.all([store.exercises.get(exerciseId), store.gyms.get(gymId)]); if (!exercise) throw new Error(`Exercise not found: ${exerciseId}`); if (!gym || gym.status === 'closed') throw new Error(`Gym unavailable: ${gymId}`);
    const groups = await store.taxonomy.groupsForExercise(exerciseId); if (!groups.length) return { exerciseId, gymId, status: 'executable', selectedRequirementGroupId: null, groupEvaluations: [], issues: [] };
    const inventory = await store.inventory.listByGym(gymId); const evaluations: RequirementGroupEvaluation[] = [];
    for (const group of groups) { const requirements = await store.taxonomy.requirementsForGroup(group.id); const results = requirements.map(requirement => { const item = inventory.find(value => value.equipmentId === requirement.equipmentId); const issues: CompatibilityIssue[] = []; let satisfied = true; if (!item) { if (requirement.level === 'required') issues.push({ code: 'missing_required_equipment', equipmentId: requirement.equipmentId, requirementId: requirement.id }); else if (requirement.level === 'preferred') issues.push({ code: 'missing_preferred_equipment', equipmentId: requirement.equipmentId, requirementId: requirement.id }); satisfied = requirement.level !== 'required'; } else if (item.status === 'unavailable') { issues.push({ code: 'equipment_unavailable', equipmentId: requirement.equipmentId, requirementId: requirement.id }); satisfied = requirement.level !== 'required'; } else { if (item.status === 'unknown') issues.push({ code: 'equipment_availability_unknown', equipmentId: requirement.equipmentId, requirementId: requirement.id }); const demand = input.context?.equipmentDemands?.find(value => !value.equipmentId || value.equipmentId === requirement.equipmentId); if (demand) { const capability = item.capabilities?.[demand.capabilityKey]; if (typeof capability !== 'number') issues.push({ code: 'unknown_capability', equipmentId: requirement.equipmentId, requirementId: requirement.id, capabilityKey: demand.capabilityKey, requiredValue: demand.requiredValue, unit: demand.unit }); else if (capability < demand.requiredValue) { issues.push({ code: 'insufficient_capability', equipmentId: requirement.equipmentId, requirementId: requirement.id, capabilityKey: demand.capabilityKey, requiredValue: demand.requiredValue, availableValue: capability, unit: demand.unit }); satisfied = requirement.level !== 'required'; } } } return { requirementId: requirement.id, equipmentId: requirement.equipmentId, level: requirement.level, satisfied, issues }; }); const issues = results.flatMap(value => value.issues); const blocking = issues.some(issue => ['missing_required_equipment','equipment_unavailable','insufficient_capability'].includes(issue.code)); const warning = issues.some(issue => !['missing_required_equipment','equipment_unavailable','insufficient_capability'].includes(issue.code)); evaluations.push({ groupId: group.id, status: blocking ? 'not_executable' : warning ? 'executable_with_warning' : 'executable', requirements: results, issues }); }
    evaluations.sort((a,b) => rank[b.status] - rank[a.status] || a.issues.length - b.issues.length || a.groupId.localeCompare(b.groupId)); const selected = evaluations[0]; return { exerciseId, gymId, status: selected.status, selectedRequirementGroupId: selected.groupId, groupEvaluations: evaluations, issues: selected.issues };
  };
  return { async matchExerciseToGym(input: MatchExerciseToGymInput): Promise<ExerciseGymMatchResult> { const base = await evaluate(input.exerciseId, input.gymId, input); if (base.status !== 'not_executable' && !input.includeAlternatives) return { ...base, alternatives: [] }; const candidates = await createCandidateResolutionService(store).resolveExerciseCandidates({ exerciseId: input.exerciseId, limit: 30, minimumScore: 0 }); const alternatives = []; for (const candidate of candidates) { const result = await evaluate(candidate.exerciseId, input.gymId, input); if (result.status !== 'not_executable') alternatives.push({ exerciseId: candidate.exerciseId, compatibilityStatus: result.status, candidateScore: candidate.score, candidateSources: candidate.sources, candidateReasons: candidate.reasons, selectedRequirementGroupId: result.selectedRequirementGroupId, issues: result.issues }); } alternatives.sort((a,b) => rank[b.compatibilityStatus] - rank[a.compatibilityStatus] || b.candidateScore - a.candidateScore || a.exerciseId.localeCompare(b.exerciseId)); return { ...base, alternatives: alternatives.slice(0, input.alternativeLimit ?? 5) }; } };
}
