export interface ExternalGymSearchInput { query: string; latitude?: number; longitude?: number; }
export interface ExternalGymResult { provider: string; externalPlaceId: string; name: string; address?: string | null; latitude?: number | null; longitude?: number | null; }
export type ExternalGymSearchResult = { status: 'available'; results: ExternalGymResult[] } | { status: 'not_configured' } | { status: 'unavailable' };
export interface ExternalGymLink { id: string; gymId: string; provider: string; externalPlaceId: string; createdAt: number; }
export interface ExternalGymProvider { search(input: ExternalGymSearchInput): Promise<ExternalGymSearchResult>; getDetails(ref: Pick<ExternalGymResult, 'provider' | 'externalPlaceId'>): Promise<{ status: 'available'; result: ExternalGymResult } | { status: 'not_configured' } | { status: 'unavailable' }>; }
export interface ExternalLinkStore { get(provider: string, externalPlaceId: string): Promise<ExternalGymLink | null>; create(link: ExternalGymLink): Promise<void>; }
export const unavailableExternalGymProvider: ExternalGymProvider = { search: async () => ({ status: 'not_configured' }), getDetails: async () => ({ status: 'not_configured' }) };
export function createGymDiscoveryService({ provider, links, gymService, importer }: { provider: ExternalGymProvider; links?: ExternalLinkStore; gymService?: { getGym(id: string): Promise<any>; createGym(input: any): Promise<any> }; importer?: { import(gym: any, link: ExternalGymLink): Promise<void> } }) { return {
  searchExternalGyms: (input: ExternalGymSearchInput) => provider.search(input), getExternalGymDetails: (ref: Pick<ExternalGymResult, 'provider' | 'externalPlaceId'>) => provider.getDetails(ref),
  async linkExternalGym(gymId: string, ref: Pick<ExternalGymResult, 'provider' | 'externalPlaceId'>) { if (!links || !gymService) throw new Error('Discovery persistence is not configured'); const gym = await gymService.getGym(gymId); if (!gym) throw new Error('Gym not found'); const existing = await links.get(ref.provider, ref.externalPlaceId); if (existing && existing.gymId !== gymId) throw new Error('External place is already linked to another Gym'); if (!existing) await links.create({ id: `${ref.provider}:${ref.externalPlaceId}`, gymId, ...ref, createdAt: Date.now() }); return gym; },
  async importExternalGym(result: ExternalGymResult) { if (!links || !gymService || !importer) throw new Error('Discovery persistence is not configured'); const existing = await links.get(result.provider, result.externalPlaceId); if (existing) return gymService.getGym(existing.gymId); const now = Date.now(); const gym = { id: `${result.provider}:${result.externalPlaceId}`, name: result.name, address: result.address ?? null, latitude: result.latitude != null && result.longitude != null ? result.latitude : null, longitude: result.latitude != null && result.longitude != null ? result.longitude : null, branchName: null, externalProvider: null, externalPlaceId: null, status: 'active', createdAt: now, updatedAt: now }; const link = { id: `link:${gym.id}`, gymId: gym.id, provider: result.provider, externalPlaceId: result.externalPlaceId, createdAt: now }; await importer.import(gym, link); return gym; },
}; }
