import { exerciseDB } from '../../lib/exercise-db';
import type { ExerciseMaster, MovementPattern, MuscleGroup } from './types';
const muscle = (value: string): MuscleGroup => ({ shoulders: 'front_delts', quadriceps: 'quads', abdominals: 'abs', 'lower back': 'erectors', 'middle back': 'upper_back', 'hip flexors': 'other' }[value] ?? value) as MuscleGroup;
const pattern = (id: string): MovementPattern => id.includes('squat') ? 'squat' : id.includes('deadlift') ? 'hinge' : id.includes('row') ? 'horizontal_pull' : id.includes('pull') ? 'vertical_pull' : id.includes('press') || id.includes('push') ? 'horizontal_push' : id.includes('curl') ? 'elbow_flexion' : id.includes('triceps') || id.includes('skull') ? 'elbow_extension' : id.includes('extension') ? 'knee_extension' : id.includes('calf') ? 'calf_raise' : id.includes('crunch') || id.includes('plank') || id.includes('raise') || id.includes('twist') ? 'core' : 'other';
const now = new Date('2026-08-23T00:00:00Z').getTime();
export const exerciseSeeds: ExerciseMaster[] = [
  ...exerciseDB.getAll().map(item => ({ id: item.id, name: item.name, aliases: [], category: item.mechanic === 'compound' ? 'compound' as const : 'isolation' as const, movementPattern: pattern(item.id), primaryMuscles: item.primaryMuscles.map(muscle), secondaryMuscles: item.secondaryMuscles.map(muscle), description: null, notes: null, status: 'active' as const, createdAt: now, updatedAt: now })),
  ['hack_squat','Hack Squat','squat','quads'], ['hip_thrust','Hip Thrust','hip_extension','glutes'], ['pec_deck','Pec Deck','horizontal_push','chest'], ['machine_chest_press','Machine Chest Press','horizontal_push','chest'], ['reverse_pec_deck','Reverse Pec Deck','horizontal_pull','rear_delts'], ['cable_lateral_raise','Cable Lateral Raise','vertical_push','side_delts'], ['high_row','High Row','horizontal_pull','upper_back'], ['cable_crunch','Cable Crunch','core','abs'], ['bulgarian_split_squat','Bulgarian Split Squat','squat','quads'], ['hip_abduction','Hip Abduction','hip_abduction','abductors'], ['hip_adduction','Hip Adduction','hip_adduction','adductors']
].map((item: any) => Array.isArray(item) ? ({ id: item[0], name: item[1], aliases: [], category: 'compound', movementPattern: item[2], primaryMuscles: [item[3]], secondaryMuscles: [], description: null, notes: null, status: 'active', createdAt: now, updatedAt: now }) : item) as ExerciseMaster[];
